### ISSUE TITLE
Add caching/fallback when unable to find the latest version

### ISSUE THREAD

**Issue by lidel** [ipfs/download-ipfs-distribution-action#12]
## Problem

Turns out https://github.com/ipfs/download-ipfs-distribution-action/pull/9 + https://github.com/ipfs/download-ipfs-distribution-action/pull/10 did not solve the problem for a scenario where user omits the version and action needs to fetch addtional metadata to find out what is the latest one:

> ![use cached dist if fetching new  fails-2022-02-11_21-17](https://user-images.githubusercontent.com/157609/153664262-dcf040e1-e40c-4234-93bb-e17d6af5a3e3.png)
> https://github.com/ipfs/distributions/runs/5136166478?check_suite_focus=true#step:3:92

This causes our nightlies to fail https://github.com/ipfs/distributions/issues/631
## Solution

I believe it is better to default to have some fallback or cached version  than to fail CI when dist.ipfs.io is unstable.

Places which we need to harden:
- [fetching /versions](https://github.com/ipfs/download-ipfs-distribution-action/blob/b4e5bd6f75b69d44e644e23ac3c7ae8c80b2f335/action.yml#L64)
- [fetching dist.json for latest version](https://github.com/ipfs/download-ipfs-distribution-action/blob/b4e5bd6f75b69d44e644e23ac3c7ae8c80b2f335/action.yml#L82)

Thoughts @aschmahmann @galargh  ?

**Comment by aschmahmann** [comment]
Having a cached fallback version to use sounds like a good idea to me 👍. If we're not already though we should make sure, for debugging purposes, to output which version we're using whenever a version is dynamically chosen
