### ISSUE TITLE
retry on curl error

### ISSUE THREAD

**Issue by lidel** [ipfs/download-ipfs-distribution-action#5]
This action uses curl multiple times. If any of the HTTP requests fails, the entire CI job will fail.
Unfortunately, out HTTP gateways are sometimes overloaded, and timeouts are more common that one would expect.

I believe we could improve devexp by retrying a few  times before returning an error that would fail the CI. 

Perhaps  `curl --retry 5` ? Afaik it is pretty good (it has exponential backoff enabled by default).  We could also  use `--retry-all-errors` if it is supported by the version of `curl` present  on github. 

Caveat: I don't think retrying plays well with redirected output – we may need to save output to a file instead, using explicit `-o filename` so it can be resumed correctly ([see this warning](https://fossies.org/linux/curl/docs/cmdline-opts/retry-all-errors.d))

**Comment by galargh** [comment]
Unfortunately, we cannot use `retry-all-errors` yet but I've added `retry` here: https://github.com/ipfs/download-ipfs-distribution-action/pull/6
